// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCmPiCAgntBG6z3C9t31U5dVyD2zudrvY',
    appId: '1:439740133222:web:746d99d5bdf24dd1ef22a7',
    messagingSenderId: '439740133222',
    projectId: 'enhn-72f48',
    authDomain: 'enhn-72f48.firebaseapp.com',
    storageBucket: 'enhn-72f48.appspot.com',
    measurementId: 'G-NPEXX617PH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBG9ERFHVtmxNaWZFQs78rGxpQKQGRK2fU',
    appId: '1:439740133222:android:250d2baca9ca4166ef22a7',
    messagingSenderId: '439740133222',
    projectId: 'enhn-72f48',
    storageBucket: 'enhn-72f48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXw2HQTApPZwsFRLSfstMSpdy97IGg1JY',
    appId: '1:439740133222:ios:7d31a5f8b7bc85a3ef22a7',
    messagingSenderId: '439740133222',
    projectId: 'enhn-72f48',
    storageBucket: 'enhn-72f48.appspot.com',
    iosBundleId: 'com.example.comidaRapida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXw2HQTApPZwsFRLSfstMSpdy97IGg1JY',
    appId: '1:439740133222:ios:7d31a5f8b7bc85a3ef22a7',
    messagingSenderId: '439740133222',
    projectId: 'enhn-72f48',
    storageBucket: 'enhn-72f48.appspot.com',
    iosBundleId: 'com.example.comidaRapida',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCmPiCAgntBG6z3C9t31U5dVyD2zudrvY',
    appId: '1:439740133222:web:99ad342da7aa15b8ef22a7',
    messagingSenderId: '439740133222',
    projectId: 'enhn-72f48',
    authDomain: 'enhn-72f48.firebaseapp.com',
    storageBucket: 'enhn-72f48.appspot.com',
    measurementId: 'G-54G49GD41Q',
  );
}
